/*

    OpenGL loader generated by glad 0.1.28 on 11/05/18 20:34:08.

    Language/Generator: D
    Specification: gl
    APIs: gl=4.6
    Profile: compatibility
    Extensions:
        GL_ARB_debug_output,
        GL_KHR_debug
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="compatibility" --api="gl=4.6" --generator="d" --spec="gl" --extensions="GL_ARB_debug_output,GL_KHR_debug"
    Online:
        http://glad.dav1d.de/#profile=compatibility&language=d&specification=gl&loader=on&api=gl%3D4.6&extensions=GL_ARB_debug_output&extensions=GL_KHR_debug
*/

module glad.gl.all;


public import glad.gl.funcs;
public import glad.gl.ext;
public import glad.gl.enums;
public import glad.gl.types;
